-- EV Car Wale: import 84 cars
-- Generated automatically from public/data/cars.json

INSERT INTO public.cars (
  brand_id,
  name,
  slug,
  price,
  price_numeric,
  range_km,
  battery_kwh,
  charging_time,
  fast_charging,
  body_type,
  seating_capacity,
  acceleration,
  top_speed,
  power,
  torque,
  fuel_type,
  image_url,
  gallery_images,
  status,
  description,
  is_active
)
VALUES
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'tata' LIMIT 1),
    'Nexon EV',
    'nexon-ev',
    '₹14.50 Lakh',
    14.5,
    465,
    40.5,
    '56 min (DC)',
    TRUE,
    'SUV',
    NULL,
    NULL,
    '150 km/h',
    '143 hp',
    NULL,
    'Electric',
    '/car_images/tata/NEXON.jpeg',
    ARRAY[]::text[],
    'latest',
    'Ventilated seats, 12.3-inch screen, V2L capability',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'tata' LIMIT 1),
    'Punch EV',
    'punch-ev',
    '₹10.99 Lakh',
    10.99,
    421,
    35,
    '56 min (DC)',
    TRUE,
    'SUV',
    NULL,
    NULL,
    '140 km/h',
    '122 hp',
    NULL,
    'Electric',
    '/car_images/tata/PUNCH.jpeg',
    ARRAY[]::text[],
    'latest',
    'Electronic parking brake, Sunroof, Paddle shifters for regeneration',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'tata' LIMIT 1),
    'Harrier EV',
    'harrier-ev',
    '₹22.00 Lakh',
    22,
    500,
    60,
    '45 min (DC)',
    TRUE,
    'SUV',
    NULL,
    NULL,
    '170 km/h',
    '218 hp',
    NULL,
    'Electric',
    '/car_images/tata/HARRIER.webp',
    ARRAY[]::text[],
    'latest',
    'AWD option, V2L & V2V charging, 12.3-inch infotainment',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'tata' LIMIT 1),
    'Curvv EV',
    'curvv-ev',
    '₹17.49 Lakh',
    17.49,
    585,
    55,
    '40 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '160 km/h',
    '167 hp',
    NULL,
    'Electric',
    '/car_images/tata/CURVE.jpeg',
    ARRAY[]::text[],
    'latest',
    'Coupe design, gesture tailgate, flush handles, Arcade.ev app suite',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'tata' LIMIT 1),
    'Tiago EV',
    'tiago-ev',
    '₹8.69 Lakh',
    8.69,
    315,
    24,
    '58 min (DC)',
    TRUE,
    'Hatchback',
    NULL,
    NULL,
    '120 km/h',
    '74 hp',
    NULL,
    'Electric',
    '/car_images/tata/TIAGO.jpeg',
    ARRAY[]::text[],
    'latest',
    'Multi-mode regen, connected car tech, cruise control',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'tata' LIMIT 1),
    'Avinya EV',
    'avinya-ev',
    '₹35.00 Lakh',
    35,
    500,
    80,
    '30 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '200 km/h',
    '350 hp',
    NULL,
    'Electric',
    '/car_images/tata/tata_avinya_ev.jpeg',
    ARRAY[]::text[],
    'latest',
    'Skateboard chassis, rotating lounge chairs, bio-degradable cabin materials',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'tata' LIMIT 1),
    'Xpres-T EV',
    'xpres-t-ev',
    '₹13.04 Lakh',
    13.04,
    391,
    32,
    '30 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '80 km/h',
    '36 hp',
    NULL,
    'Electric',
    '/car_images/tata/EXPRESS-T.jpeg',
    ARRAY[]::text[],
    'latest',
    'Multi-mode regen, driving modes, automatic climate control',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'tata' LIMIT 1),
    'Sierra EV',
    'sierra-ev',
    '₹25.00 Lakh',
    25,
    500,
    60,
    '40 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '160 km/h',
    '200 hp',
    NULL,
    'Electric',
    '/car_images/tata/SIERRA.jpeg',
    ARRAY[]::text[],
    'latest',
    'Signature split glass house, premium captain lounge, high-end upholstery',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mahindra' LIMIT 1),
    'XUV400',
    'xuv400',
    '₹15.49 Lakh',
    15.49,
    456,
    39.4,
    '50 min (DC)',
    TRUE,
    'SUV',
    NULL,
    NULL,
    '160 km/h',
    '150 hp',
    NULL,
    'Electric',
    '/car_images/mahindra/mahindra_XUV_400.jpg',
    ARRAY[]::text[],
    'latest',
    'Single pane sunroof, Drive modes, 10.25-inch touchscreen',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mahindra' LIMIT 1),
    'BE6',
    'be6',
    '₹24.00 Lakh',
    24,
    450,
    60,
    '30 min (DC)',
    TRUE,
    'SUV',
    NULL,
    NULL,
    '180 km/h',
    '280 hp',
    NULL,
    'Electric',
    '/car_images/mahindra/mahindra-BE6.jpeg',
    ARRAY[]::text[],
    'latest',
    'Futuristic design, Digital cockpit, Advanced ADAS',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mahindra' LIMIT 1),
    'XEV 9e',
    'xev-9e',
    '₹38.00 Lakh',
    38,
    533,
    79,
    '35 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '180 km/h',
    '286 hp',
    NULL,
    'Electric',
    '/car_images/mahindra/mahindra_XEV_9e.webp',
    ARRAY[]::text[],
    'latest',
    'Triple screen console, Augmented reality HUD, futuristic silhouette',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mahindra' LIMIT 1),
    'Thar.e',
    'thar-e',
    '₹25.00 Lakh',
    25,
    450,
    60,
    '45 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '160 km/h',
    '250 hp',
    NULL,
    'Electric',
    '/car_images/mahindra/thar.e.jpeg',
    ARRAY[]::text[],
    'latest',
    'Rugged off-road capability, modular design, waterproof interior',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mahindra' LIMIT 1),
    'BE 07',
    'be-07',
    '₹29.00 Lakh',
    29,
    450,
    80,
    '30 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '160 km/h',
    '285 hp',
    NULL,
    'Electric',
    '/car_images/mahindra/mahindra_BE_07.jpeg',
    ARRAY[]::text[],
    'latest',
    'Triple screen dashboard layout, Level 2+ ADAS, panoramic sunroof',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mahindra' LIMIT 1),
    'XEV 9s',
    'xev-9s',
    '₹19.95 Lakh',
    19.95,
    679,
    79,
    '20 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '202 km/h',
    '378 hp',
    NULL,
    'Electric',
    '/car_images/mahindra/Mahindra XEV 9s.png',
    ARRAY[]::text[],
    'latest',
    '7-seater layout, openable panoramic sunroof, ventilated front seats, 5 drive modes',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mahindra' LIMIT 1),
    'XUV 3XO EV',
    'xuv-3xo-ev',
    '₹13.89 Lakh',
    13.89,
    456,
    39.4,
    '50 min (DC)',
    TRUE,
    'SUV',
    NULL,
    NULL,
    '150 km/h',
    '198 hp',
    NULL,
    'Electric',
    '/car_images/mahindra/3X0.jpeg',
    ARRAY[]::text[],
    'latest',
    'Level 2 ADAS, panoramic sunroof, twin 10.25-inch screens, dual-zone climate control',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mg' LIMIT 1),
    'Cyberster',
    'cyberster',
    '₹82.50 Lakh',
    82.5,
    580,
    77,
    '40 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '200 km/h',
    '503 hp',
    NULL,
    'Electric',
    '/car_images/MG/MG_Cyberster.jpeg',
    ARRAY[]::text[],
    'latest',
    'Electric scissor doors, weatherproof convertible soft top, triple screen cockpit, Level 2 ADAS',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mg' LIMIT 1),
    'M9 EV',
    'm9-ev',
    '₹79.95 Lakh',
    79.95,
    548,
    90,
    '90 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '180 km/h',
    '242 hp',
    NULL,
    'Electric',
    '/car_images/MG/MG_M9.jpeg',
    ARRAY[]::text[],
    'latest',
    '16-way adjustable second-row Presidential Ottoman seats with massage, dual sunroofs, 13 JBL speakers',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mg' LIMIT 1),
    'ZS EV',
    'zs-ev',
    '₹17.99 Lakh',
    17.99,
    461,
    50.3,
    '60 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '140 km/h',
    '174 hp',
    NULL,
    'Electric',
    '/car_images/MG/MG ZS EV.JPG',
    ARRAY[]::text[],
    'latest',
    'Panoramic sunroof, Level 2 ADAS (Essence trim), 360-degree camera, wireless charger',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mg' LIMIT 1),
    'Comet EV',
    'comet-ev',
    '₹7.80 Lakh',
    7.8,
    230,
    17.3,
    '3.5 hours (AC)',
    FALSE,
    'Hatchback',
    NULL,
    NULL,
    '100 km/h',
    '42 hp',
    NULL,
    'Electric',
    '/car_images/MG/mg_comet_ev.webp',
    ARRAY[]::text[],
    'latest',
    'Dual 10.25-inch integrated screens, wireless Apple CarPlay & Android Auto, connected car tech, rear parking camera',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'hyundai' LIMIT 1),
    'Ioniq 5',
    'ioniq-5',
    '₹46.05 Lakh',
    46.05,
    631,
    72.6,
    '18 min (DC)',
    TRUE,
    'SUV',
    NULL,
    NULL,
    '185 km/h',
    '217 hp',
    NULL,
    'Electric',
    '/car_images/hyundai/hyundai_ioniq5.jpeg',
    ARRAY[]::text[],
    'latest',
    'Dual screens, Relaxion seats, V2L, Premium Bose Sound',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'hyundai' LIMIT 1),
    'Ioniq 6',
    'ioniq-6',
    '₹65.00 Lakh',
    65,
    614,
    77.4,
    '18 min (DC)',
    TRUE,
    'SUV',
    NULL,
    NULL,
    '250 km/h',
    '320 hp',
    NULL,
    'Electric',
    '/car_images/hyundai/Hyundai_IONIQ6.jpeg',
    ARRAY[]::text[],
    'latest',
    'Aerodynamic streamliner, interactive lighting, dual motors',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'hyundai' LIMIT 1),
    'Creta EV',
    'creta-ev',
    '₹18.03 Lakh',
    18.03,
    510,
    51.4,
    '58 min (DC)',
    TRUE,
    'SUV',
    NULL,
    NULL,
    '180 km/h',
    '171 hp',
    NULL,
    'Electric',
    '/car_images/hyundai/Hyundai_Creta_Electric.jpeg',
    ARRAY[]::text[],
    'latest',
    'Twin 10.25-inch integrated displays, Level 2 ADAS (20+ features), panoramic sunroof, ventilated front seats, Bose audio system',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'byd' LIMIT 1),
    'BYD Seal',
    'byd-seal',
    '₹41.00 Lakh',
    41,
    650,
    82.5,
    '26 min (DC)',
    TRUE,
    'Sedan',
    NULL,
    NULL,
    '240 km/h',
    '530 hp',
    NULL,
    'Electric',
    '/car_images/BYD/byd_seal.jpeg',
    ARRAY[]::text[],
    'latest',
    'Rotating screen, Cell-to-body tech, Head-up display',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'byd' LIMIT 1),
    'BYD Atto 3',
    'byd-atto3',
    '₹24.99 Lakh',
    24.99,
    521,
    60.48,
    '50 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '160 km/h',
    '201 hp',
    NULL,
    'Electric',
    '/car_images/BYD/BYD_atto.jpeg',
    ARRAY[]::text[],
    'latest',
    'Blade battery, rotation screen, panoramic roof, ambient lighting',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'byd' LIMIT 1),
    'Sealion 6',
    'byd-sealion-6',
    '₹35.00 Lakh',
    35,
    1092,
    18.3,
    '30 min (DC)',
    TRUE,
    'Sedan',
    NULL,
    NULL,
    '179 km/h',
    '324 hp',
    NULL,
    'Electric',
    '/car_images/BYD/BYD-SEALION-6.jpeg',
    ARRAY[]::text[],
    'latest',
    'DM-i plug-in hybrid architecture, 15.6-inch rotating hub, 10-speaker Infinity audio, dual wireless charging pads',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'byd' LIMIT 1),
    'eMax 7',
    'byd-emax-7',
    '₹26.90 Lakh',
    26.9,
    530,
    71.8,
    '56 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '180 km/h',
    '201 hp',
    NULL,
    'Electric',
    '/car_images/BYD/BYD_eMAX_7.jpeg',
    ARRAY[]::text[],
    'latest',
    '6 or 7-seater layout adjustments, rotating touchscreen infotainment, panoramic sunroof, Level 2 ADAS suite',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'byd' LIMIT 1),
    'Sealion 7',
    'byd-sealion-7',
    '₹49.90 Lakh',
    49.9,
    567,
    82.56,
    '24 min (DC)',
    TRUE,
    'Sedan',
    NULL,
    NULL,
    '215 km/h',
    '523 hp',
    NULL,
    'Electric',
    '/car_images/BYD/BYD SEALION 7.jpeg',
    ARRAY[]::text[],
    'latest',
    '11 airbags configuration, soundproof double-glazed acoustic glass, frequency-selective damping (FSD) shocks',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'kia' LIMIT 1),
    'Kia EV6',
    'kia-ev6',
    '₹49.00 Lakh',
    49,
    708,
    77.4,
    '18 min (DC)',
    TRUE,
    'SUV',
    NULL,
    NULL,
    '192 km/h',
    '325 hp',
    NULL,
    'Electric',
    '/car_images/KIA/kia_ev6.jpeg',
    ARRAY[]::text[],
    'latest',
    'Augmented reality HUD, Sunroof, Meridian Audio',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'kia' LIMIT 1),
    'EV9',
    'kia-ev9',
    '₹1.10 Crore',
    110,
    561,
    99.8,
    '24 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '200 km/h',
    '384 hp',
    NULL,
    'Electric',
    '/car_images/KIA/kia_ev9.jpeg',
    ARRAY[]::text[],
    'latest',
    '3-row seating, Swivel seats, dual sunroof, LiDAR-ready ADAS',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'kia' LIMIT 1),
    'Syros EV',
    'syros-ev',
    '₹15.00 Lakh',
    15,
    350,
    35,
    '40 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '150 km/h',
    '150 hp',
    NULL,
    'Electric',
    '/car_images/KIA/Kia_syros_ev.jpeg',
    ARRAY[]::text[],
    'latest',
    'Connected telematics, tall-boy stance, compact city footprint',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'bmw' LIMIT 1),
    'BMW i4',
    'bmw-i4',
    '₹72.50 Lakh',
    72.5,
    590,
    83.9,
    '31 min (DC)',
    TRUE,
    'Sedan',
    NULL,
    NULL,
    '190 km/h',
    '340 hp',
    NULL,
    'Electric',
    '/car_images/BMW/bmw_i4.jpeg',
    ARRAY[]::text[],
    'latest',
    'Curved display, Reversing assistant, Glass roof',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'bmw' LIMIT 1),
    'i7',
    'bmw-i7',
    '₹2.05 Crore',
    205,
    625,
    101.7,
    '50 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '250 km/h',
    '536 hp',
    NULL,
    'Electric',
    '/car_images/BMW/bmw_i7.jpeg',
    ARRAY[]::text[],
    'latest',
    '31.3-inch 8K roof-mounted Theatre Screen, dual 5.5-inch door touchscreens, 35-speaker Bowers & Wilkins system',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'bmw' LIMIT 1),
    'iX',
    'bmw-ix',
    '₹1.40 Crore',
    140,
    575,
    111.5,
    '35 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '200 km/h',
    '516 hp',
    NULL,
    'Electric',
    '/car_images/BMW/BMW iX.jpeg',
    ARRAY[]::text[],
    'latest',
    'BMW Curved Display with iDrive 8.5, Harman Kardon surround sound, frameless doors with electric openers, 22-inch aero alloys',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'bmw' LIMIT 1),
    'iX1 LWB',
    'bmw-ix1',
    '₹51.40 Lakh',
    51.4,
    531,
    66.4,
    '30 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '175 km/h',
    '204 hp',
    NULL,
    'Electric',
    '/car_images/BMW/BMW iX1 LWB.jpeg',
    ARRAY[]::text[],
    'latest',
    'Extended Long Wheelbase configuration, BMW Curved Display with iDrive 9, large panoramic glass roof, 12-speaker audio system',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'bmw' LIMIT 1),
    'i5 M60',
    'bmw-i5',
    '₹1.20 Crore',
    120,
    516,
    83.9,
    '30 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '230 km/h',
    '592 hp',
    NULL,
    'Electric',
    '/car_images/MG/IM5.jpeg',
    ARRAY[]::text[],
    'latest',
    'BMW Interaction Bar with crystal-look ambient surface, Bowers & Wilkins surround sound, M-specific performance elements',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'audi' LIMIT 1),
    'Q6 e-tron',
    'audi-q6-e-tron',
    '₹88.00 Lakh',
    88,
    625,
    100,
    '21 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '210 km/h',
    '380 hp',
    NULL,
    'Electric',
    '/car_images/AUDI/Audi Q6 e-tron.jpeg',
    ARRAY[]::text[],
    'latest',
    '14.5-inch curved MMI display, 10.9-inch front passenger screen, 800V architecture, Bang & Olufsen 3D sound system',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'audi' LIMIT 1),
    'e-tron GT',
    'audi-e-tron-gt',
    '₹1.72 Crore',
    172,
    488,
    93.4,
    '22.5 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '245 km/h',
    '523 hp',
    NULL,
    'Electric',
    '/car_images/AUDI/audi_etron_gt.jpg',
    ARRAY[]::text[],
    'latest',
    'quattro electric AWD, Matrix LED headlamps with laser light, adaptive air suspension, active rear spoiler',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'audi' LIMIT 1),
    'A6 e-tron',
    'audi-a6-e-tron',
    '₹75.00 Lakh',
    75,
    756,
    100,
    '21 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '210 km/h',
    '367 hp',
    NULL,
    'Electric',
    '/car_images/AUDI/AUDI-A6-ETRON.png',
    ARRAY[]::text[],
    'latest',
    'Ultra-low 0.21 drag coefficient, triple-screen dashboard layout, digital side mirrors option, second-generation virtual light alleys',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'blinq' LIMIT 1),
    'Ryde',
    'ryde',
    '₹12.50 Lakh',
    12.5,
    312,
    28.8,
    '45 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '120 km/h',
    '74 hp',
    NULL,
    'Electric',
    '/car_images/BLINQ/RYDE.jpeg',
    ARRAY[]::text[],
    'latest',
    'Dual 10.25-inch integrated display, smart ambient theme lighting, connected car software ecosystem',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'genesis' LIMIT 1),
    'GV60',
    'gv60',
    '₹65.00 Lakh',
    65,
    481,
    84,
    '18 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '235 km/h',
    '429 hp',
    NULL,
    'Electric',
    '/car_images/GENESIS/GV60.jpeg',
    ARRAY[]::text[],
    'latest',
    'Crystal Sphere gear selector, Face Connect biometric validation, Boost Mode throttle architecture, 17-speaker Bang & Olufsen audio',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'citroen' LIMIT 1),
    'eC3 X',
    'ec3',
    '₹11.99 Lakh',
    11.99,
    325,
    29.2,
    '57 min (DC)',
    TRUE,
    'Hatchback',
    NULL,
    NULL,
    '107 km/h',
    '56 hp',
    NULL,
    'Electric',
    '/car_images/CITROEN/Citroen_eC3.jpeg',
    ARRAY[]::text[],
    'latest',
    '10.25-inch MyCitroen Play touchscreen, optional 6-speaker JBL audio array, 180 mm ground clearance layout',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'ferrari' LIMIT 1),
    'Luce',
    'luce',
    '₹6.10 Crore',
    610,
    530,
    122,
    '18 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '310 km/h',
    '1035 hp',
    NULL,
    'Electric',
    '/car_images/ferrari/LUCE.jpeg',
    ARRAY[]::text[],
    'latest',
    'Quad-motor AWD setup, 8-layer multi-layered Samsung OLED instrument display, structural battery chassis alignment, active aerodynamic floating bridge',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'honda' LIMIT 1),
    'Elevate EV',
    'elevate-ev',
    '₹18.00 Lakh',
    18,
    470,
    55,
    '30 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '160 km/h',
    '174 hp',
    NULL,
    'Electric',
    '/car_images/HONDA/honda_elevate_EV.jpeg',
    ARRAY[]::text[],
    'latest',
    'Honda Sensing ADAS framework, 220 mm absolute ground clearance profile, FWD permanent magnet motor matrix',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'honda' LIMIT 1),
    '0 Alpha',
    'zero-alpha',
    '₹20.00 Lakh',
    20,
    500,
    65,
    '15 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '180 km/h',
    '241 hp',
    NULL,
    'Electric',
    '/car_images/HONDA/ZERO_ALPHA.jpeg',
    ARRAY[]::text[],
    'latest',
    'Thin-Light-Wise architecture framework, U-shaped digital cockpit signature bar, 19-inch specialized aero alloy wheels',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'isuzu' LIMIT 1),
    'D-Max EV',
    'd-max-ev',
    '₹35.00 Lakh',
    35,
    300,
    66.3,
    '45 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '130 km/h',
    '175 hp',
    NULL,
    'Electric',
    '/car_images/ISUZU/D-MAX-EV.jpeg',
    ARRAY[]::text[],
    'latest',
    'Dual-motor full-time AWD pickup architecture, 1000 kg payload capacity framework, 3.5 tonnes heavy towing rig points',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'nissan' LIMIT 1),
    'Ariya',
    'nissan-ariya',
    '₹60.00 Lakh',
    60,
    529,
    87,
    '40 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '200 km/h',
    '389 hp',
    NULL,
    'Electric',
    '/car_images/NISSAN/Nissan_Ariya.jpeg',
    ARRAY[]::text[],
    'latest',
    'Dual 12.3-inch floating dashboards, ProPILOT Assist 2.0 driver suite, e-4ORCE twin-motor AWD layout, sliding center console',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'nissan' LIMIT 1),
    'Leaf',
    'nissan-leaf',
    '₹40.00 Lakh',
    40,
    363,
    40,
    '60 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '144 km/h',
    '147 hp',
    NULL,
    'Electric',
    '/car_images/NISSAN/nissan_leaf.JPG',
    ARRAY[]::text[],
    'latest',
    'e-Pedal single-pedal drive mode matrix, NissanConnect infotainment hub, intelligent cruise integration layout',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mini' LIMIT 1),
    'Countryman Electric',
    'mini-countryman-electric',
    '₹54.90 Lakh',
    54.9,
    462,
    66.45,
    '29 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '170 km/h',
    '204 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/porsche_maccan_EV.jpeg',
    ARRAY[]::text[],
    'latest',
    '240mm round OLED high-res cluster, Level 2 ADAS assist frameworks, customized Go-Kart driving theme tracks',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'jeep' LIMIT 1),
    'Avenger EV',
    'jeep-avengers',
    '₹25.00 Lakh',
    25,
    400,
    54,
    '34 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '150 km/h',
    '154 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/PORSCHE_TAYCAN.JPG',
    ARRAY[]::text[],
    'latest',
    'Selec-Terrain dynamic traction layout, 10.25-inch Uconnect display grid, 360-degree shielding protection cladding panel matrix',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'lexus' LIMIT 1),
    'ES 500e',
    'lexus-es',
    '₹89.99 Lakh',
    89.99,
    580,
    74.68,
    '28 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '210 km/h',
    '338 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/cayenne_ev-COLORS/Carrara White Metallic.webp',
    ARRAY[]::text[],
    'latest',
    'Electrochromic glass roof opaque control switcher, 14-inch massive glass hub terminal, 17-speaker Mark Levinson premium array',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'lotus' LIMIT 1),
    'Eletre R',
    'lotus-eletre',
    '₹2.55 Crore',
    255,
    490,
    112,
    '20 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '265 km/h',
    '905 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/porsche_maccan_EV.jpeg',
    ARRAY[]::text[],
    'latest',
    'Active aerodynamics rear wing flap control, deployable LiDAR safety architecture, 23-speaker KEF Reference system matrix',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'lotus' LIMIT 1),
    'Emeya GT',
    'lotus-emeya',
    '₹2.34 Crore',
    234,
    610,
    102,
    '14 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '250 km/h',
    '905 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/cayenne_ev-COLORS/Carrara White Metallic.webp',
    ARRAY[]::text[],
    'latest',
    'Active front grille array gate, electronically controlled air suspension tracks, twin-layer sport race cockpit architecture',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'maruti_suzuki' LIMIT 1),
    'e Vitara',
    'maruti-e-vitara',
    '₹15.99 Lakh',
    15.99,
    543,
    61,
    '45 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '160 km/h',
    '181 hp',
    NULL,
    'Electric',
    '/car_images/maruti suzuki/maruti_evitara.jpeg',
    ARRAY[]::text[],
    'latest',
    '7 Airbags architecture implementation as stock, dual-screen instrumentation deck, e-AllGrip e-AWD snow traction selector systems',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'maruti_suzuki' LIMIT 1),
    'Fronx EV',
    'fronx-ev',
    '₹12.00 Lakh',
    12,
    400,
    48,
    '45 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '140 km/h',
    '138 hp',
    NULL,
    'Electric',
    '/car_images/maruti suzuki/fronx_ev.jpeg',
    ARRAY[]::text[],
    'latest',
    '9-inch SmartPlay Pro+ touchscreen display, 360-degree camera matrix, regenerative braking with single-pedal drive capability',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'maruti_suzuki' LIMIT 1),
    'Jimny EV',
    'jimny-ev',
    '₹18.00 Lakh',
    18,
    350,
    60,
    '50 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '130 km/h',
    '156 hp',
    NULL,
    'Electric',
    '/car_images/maruti suzuki/IMG_2402.jpeg',
    ARRAY[]::text[],
    'latest',
    'Dual-motor AllGrip AWD electric terrain system, structural boxy ladder-frame chassis layout, scratch-resistant interior utility tracking',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mercedes_benz' LIMIT 1),
    'CLA EV',
    'mercedes-benz-cla-ev',
    '₹55.00 Lakh',
    55,
    792,
    85.5,
    '20 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '210 km/h',
    '268 hp',
    NULL,
    'Electric',
    '/car_images/MERCEDES_BENZ/Mercedes_Benz_CLA.jpeg',
    ARRAY[]::text[],
    'latest',
    '800V high-efficiency architecture, MBUX Superscreen with passenger display, active lane keep assist, ambient lighting matrix',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mercedes_benz' LIMIT 1),
    'EQS SUV',
    'mercedes-benz-eqs-suv',
    '₹1.41 Crore',
    141,
    609,
    118,
    '31 min (DC)',
    TRUE,
    'SUV',
    NULL,
    NULL,
    '210 km/h',
    '536 hp',
    NULL,
    'Electric',
    '/car_images/MERCEDES_BENZ/Mercedes-Benz_EQS_SUV.jpeg',
    ARRAY[]::text[],
    'latest',
    '56-inch MBUX Hyperscreen cockpit, rear-axle steering layout, luxury Airmatic air suspension matrix, 3rd row 7-seater layout',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mercedes_benz' LIMIT 1),
    'G-Class EV',
    'mercedes-benz-g-class-ev',
    '₹2.70 Crore',
    270,
    473,
    116,
    '32 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '180 km/h',
    '579 hp',
    NULL,
    'Electric',
    '/car_images/MERCEDES_BENZ/Mercedes_Benz_CLA.jpeg',
    ARRAY[]::text[],
    'latest',
    'Quad-motor individual drive setup, G-TURN 360 tank-turn capability, low-range off-road gear reduction system, ladder-frame protective casing',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mercedes_benz' LIMIT 1),
    'AMG EQS 53',
    'mercedes-benz-amg-eqs',
    '₹2.45 Crore',
    245,
    526,
    107.8,
    '31 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '250 km/h',
    '751 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/porsche_maccan_EV.jpeg',
    ARRAY[]::text[],
    'latest',
    '56-inch MBUX Hyperscreen with AMG performance displays, dynamic 9-degree rear-axle steering, AMG RIDE CONTROL+ air suspension',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mercedes_benz' LIMIT 1),
    'C-Class EV',
    'mercedes-benz-c-class-ev',
    '₹80.00 Lakh',
    80,
    762,
    100,
    '22 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '210 km/h',
    '360 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/cayenne_ev-COLORS/Carrara White Metallic.webp',
    ARRAY[]::text[],
    'latest',
    'Next-generation MB.EA electric architecture, radical aerodynamic styling matrix, standalone advanced panoramic cockpit HUD',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'mercedes_benz' LIMIT 1),
    'Maybach EQS SUV 680',
    'mercedes-benz-eqs-maybach',
    '₹2.40 Crore',
    240,
    611,
    122,
    '31 min (DC)',
    TRUE,
    'SUV',
    NULL,
    NULL,
    '210 km/h',
    '649 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/cayenne_ev-COLORS/Carrara White Metallic.webp',
    ARRAY[]::text[],
    'latest',
    'First-class rear lounge architecture, executive calf-massage seating system, bespoke Maybach driving program, 15-speaker premium sound system',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'pmv' LIMIT 1),
    'EaS-E',
    'pmv-eas-e',
    '₹4.79 Lakh',
    4.79,
    160,
    10,
    '4 hours (AC)',
    FALSE,
    NULL,
    NULL,
    NULL,
    '70 km/h',
    '13.4 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/cayenne_ev-COLORS/Carrara White Metallic.webp',
    ARRAY[]::text[],
    'latest',
    'Feet-free driving dashboard setup, Remote Parking Assist capability, micro-mobility tandem two-seater layout, smart connected diagnostics',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'renault' LIMIT 1),
    'Kwid EV',
    'renault-kwid-ev',
    '₹9.50 Lakh',
    9.5,
    271,
    26.8,
    '50 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '110 km/h',
    '44 hp',
    NULL,
    'Electric',
    '/car_images/RENAULT/renault_kwid_ev.JPG',
    ARRAY[]::text[],
    'latest',
    '8-inch touchscreen media display layout, dynamic reverse parking camera, absolute daily urban eco-drive monitoring tracks',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'porsche' LIMIT 1),
    'Macan EV',
    'porsche-macan-ev',
    '₹1.65 Crore',
    165,
    613,
    100,
    '21 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '220 km/h',
    '402 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/PORSCHE_TAYCAN.JPG',
    ARRAY[]::text[],
    'latest',
    '800V high-performance PPE architecture, Porsche Active Suspension Management (PASM), dual-screen dashboard with augmented reality HUD',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'porsche' LIMIT 1),
    'Taycan',
    'porsche-taycan',
    '₹1.89 Crore',
    189,
    678,
    105,
    '18 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '250 km/h',
    '429 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/PORSCHE_TAYCAN.JPG',
    ARRAY[]::text[],
    'latest',
    'Performance Battery Plus architecture, curved floating digital cluster panel, adaptive air suspension layout matrix, torque vectoring plus',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'porsche' LIMIT 1),
    'Cayenne Electric',
    'porsche-cayenne-ev',
    '₹1.77 Crore',
    177,
    642,
    113,
    '16 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '230 km/h',
    '436 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/PORSCHE_TAYCAN.JPG',
    ARRAY[]::text[],
    'latest',
    '800V Premium Platform Electric (PPE) architecture, HD-Matrix LED display highlights, Porsche Driver Experience curved panel, adaptive air suspension with PASM',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'rolls_royce' LIMIT 1),
    'Spectre',
    'rolls-royce-spectre',
    '₹7.50 Crore',
    750,
    530,
    102,
    '34 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '250 km/h',
    '584 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/porsche_maccan_EV.jpeg',
    ARRAY[]::text[],
    'latest',
    'Starlight doors configuration panel system, planar suspension decoupling architecture framework, bespoke luxury audio soundscaping, ultra-silent insulation',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'toyota' LIMIT 1),
    'bZ4X',
    'toyota-bz4x',
    '₹60.00 Lakh',
    60,
    516,
    71.4,
    '30 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '160 km/h',
    '204 hp',
    NULL,
    'Electric',
    '/car_images/TOYOTA/Toyota_bZ4X.jpeg',
    ARRAY[]::text[],
    'latest',
    'Modular e-TNGA architecture layout, Subaru co-developed X-MODE terrain matrix, floating widescreen multimedia console, wireless smartphone hub integration',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'toyota' LIMIT 1),
    'Urban Cruiser EV',
    'toyota-Urban-Cruiser-ev',
    '₹12.50 Lakh',
    12.5,
    400,
    48,
    '45 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '140 km/h',
    '138 hp',
    NULL,
    'Electric',
    '/car_images/TOYOTA/Toyota_Urban_Cruiser.jpeg',
    ARRAY[]::text[],
    'latest',
    '9-inch smart multimedia console display system, 360-degree top panoramic monitoring matrix, multi-stage smart regenerative braking logic',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'tesla' LIMIT 1),
    'Model Y',
    'tesla-model-y',
    '₹50.90 Lakh',
    50.9,
    533,
    75,
    '27 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '217 km/h',
    '384 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/cayenne_ev-COLORS/Carrara White Metallic.webp',
    ARRAY[]::text[],
    'latest',
    '15-inch central interactive touchscreen hub, Autopilot safety hardware suite stack, full-glass tint panoramic roof assembly, expansive 2100+ liters utility space',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'skoda' LIMIT 1),
    'Elroq',
    'skoda-elroq',
    '₹30.00 Lakh',
    30,
    580,
    77,
    '25 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '180 km/h',
    '282 hp',
    NULL,
    'Electric',
    '/car_images/SKODA/Skoda_Elroq.jpeg',
    ARRAY[]::text[],
    'latest',
    'Tech-Deck Face gloss panel, 13-inch standalone infotainment cluster, sustainable Recytitan textile trims, Level 2 ADAS track',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'skoda' LIMIT 1),
    'Enyaq iV',
    'skoda-enyaq',
    '₹50.00 Lakh',
    50,
    550,
    82,
    '28 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '180 km/h',
    '282 hp',
    NULL,
    'Electric',
    '/car_images/SKODA/Skoda_Enyaq.JPG',
    ARRAY[]::text[],
    'latest',
    'Crystal Face illuminated grille matrix, 13-inch center console display, panoramic glass canopy, massager front seating profiles',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'strom_motors' LIMIT 1),
    'R3',
    'strom-r3',
    '₹4.50 Lakh',
    4.5,
    200,
    30,
    '3 hours (AC)',
    FALSE,
    NULL,
    NULL,
    NULL,
    '80 km/h',
    '20 hp',
    NULL,
    'Electric',
    '/car_images/VINFAST/vin_fast_vf3.jpeg',
    ARRAY[]::text[],
    'latest',
    'Tandem 2-seater configuration, 7-inch auxiliary infotainment system screen, dual front storage compartments, customized IoT diagnostic tech',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'pravaig' LIMIT 1),
    'Defy',
    'pravaig-defy',
    '₹39.50 Lakh',
    39.5,
    500,
    90.9,
    '30 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '210 km/h',
    '402 hp',
    NULL,
    'Electric',
    '/car_images/PORSCHE/porsche_maccan_EV.jpeg',
    ARRAY[]::text[],
    'latest',
    'Devialet immersive sound architecture, 15.6-inch ultra-widescreen layout interface, 234mm extreme off-road ground clearance, PM2.5 multi-stage cabin filters',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'volvo' LIMIT 1),
    'EC40',
    'volvo-ec40',
    '₹62.50 Lakh',
    62.5,
    530,
    78,
    '27 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '180 km/h',
    '408 hp',
    NULL,
    'Electric',
    '/car_images/VOLVO/volvo_EC40.WEBP',
    ARRAY[]::text[],
    'latest',
    'Pixel LED steering beam lighting matrix, Harman Kardon audio integration, eco leather-free interior composite textures, panoramic roof',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'volvo' LIMIT 1),
    'EX30',
    'volvo-ex30',
    '₹45.00 Lakh',
    45,
    476,
    69,
    '26 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '180 km/h',
    '272 hp',
    NULL,
    'Electric',
    '/car_images/VOLVO/VOLVO_EX30.jpeg',
    ARRAY[]::text[],
    'latest',
    'Dashboard audio soundbar integration, minimalist central context control layout display, ambient interior theme light tracks, active park assist',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'volvo' LIMIT 1),
    'EX40',
    'volvo-ex40',
    '₹56.10 Lakh',
    56.1,
    475,
    69,
    '28 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '180 km/h',
    '238 hp',
    NULL,
    'Electric',
    '/car_images/maruti suzuki/IMG_2402.jpeg',
    ARRAY[]::text[],
    'latest',
    'Google built-in OS architecture network, structural clean-cabin filtration layer air systems, advanced digital driver safety monitors',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'volvo' LIMIT 1),
    'EX90',
    'volvo-ex90',
    '₹1.20 Crore',
    120,
    600,
    111,
    '30 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '180 km/h',
    '517 hp',
    NULL,
    'Electric',
    '/car_images/VOLVO/Volvo_EX90.jpeg',
    ARRAY[]::text[],
    'latest',
    'Roof-mounted LiDAR core scanner integration, 7-seater absolute luxury layout configuration, Bowers & Wilkins Dolby Atmos structural array, ocean-bound plastic components',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'volkswagen' LIMIT 1),
    'ID.4',
    'volkswagen-id4',
    '₹42.00 Lakh',
    42,
    520,
    82,
    '26 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '180 km/h',
    '282 hp',
    NULL,
    'Electric',
    '/car_images/tata/NEXON.jpeg',
    ARRAY[]::text[],
    'latest',
    'ID.Light communicative intelligent dash indicator strips, 12-inch active composition touchscreen, panoramic dark tint sunroof, IQ.DRIVE assist suite',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'vayve_mobility' LIMIT 1),
    'Eva',
    'vayve-mobility-eva',
    '₹3.99 Lakh',
    3.99,
    250,
    14,
    '45 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '70 km/h',
    '16 hp',
    NULL,
    'Electric',
    '/car_images/VAYVE_MOBILITY/eva.jpeg',
    ARRAY[]::text[],
    'latest',
    'Tandem smart 2+1 seating city layout, panoramic glass viewing canopy dome, solar auxiliary charging roof panel stack addition, localized drive controls',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'vinfast' LIMIT 1),
    'VF 3',
    'vinfast-vf3',
    '₹9.99 Lakh',
    9.99,
    210,
    18.4,
    '36 min (DC)',
    TRUE,
    'SUV',
    NULL,
    NULL,
    '100 km/h',
    '43 hp',
    NULL,
    'Electric',
    '/car_images/VINFAST/vin_fast_vf3.jpeg',
    ARRAY[]::text[],
    'latest',
    '10-inch essential infotainment dashboard screen, high-clearance off-road micro-SUV stance setup, collapsible rear storage maximization option',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'vinfast' LIMIT 1),
    'VF 6',
    'vinfast-vf6',
    '₹22.00 Lakh',
    22,
    399,
    59.6,
    '30 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '150 km/h',
    '174 hp',
    NULL,
    'Electric',
    '/car_images/VINFAST/VinFast VF 6.jpeg',
    ARRAY[]::text[],
    'latest',
    'Open layouts central interaction hub console screen, HUD digital projection layout, Pininfarina co-developed exterior profile lines, Level 2 ADAS track',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'vinfast' LIMIT 1),
    'VF 7',
    'vinfast-vf7',
    '₹32.00 Lakh',
    32,
    431,
    75.3,
    '25 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '200 km/h',
    '348 hp',
    NULL,
    'Electric',
    '/car_images/VINFAST/vin_fast_vf7.jpeg',
    ARRAY[]::text[],
    'latest',
    'Dual-motor specialized AWD layout integration, 12.9-inch interactive driver command system screen, glass panoramic sky roof track, high-performance styling lines',
    TRUE
  ),
(
    (SELECT id FROM public.brands WHERE LOWER(name) = 'vinfast' LIMIT 1),
    'VF MPV 7',
    'vinfast-vf-mpv7',
    '₹36.00 Lakh',
    36,
    418,
    75.3,
    '28 min (DC)',
    TRUE,
    NULL,
    NULL,
    NULL,
    '185 km/h',
    '348 hp',
    NULL,
    'Electric',
    '/car_images/VINFAST/VinFast VF MPV7.JPG',
    ARRAY[]::text[],
    'latest',
    'Three-row multi-purpose utility seating array layout, customizable modular cargo zones tracker, comprehensive smart security system shielding',
    TRUE
  );

