// --- Image Mapping Database ---
// Main S3 image mapping for all EV models
const S3_IMAGE_MAPPING = {
      "audi-a6-e-tron": "car_images/AUDI/AUDI-A6-ETRON.jpg",
      "audi-e-tron-gt": "car_images/AUDI/audi_etron_gt.jpg",
      "audi-q6-e-tron": "car_images/AUDI/Audi Q6 e-tron.jpeg",
      "audi-q6-etron": "car_images/AUDI/Audi Q6 e-tron.jpeg",
      "audi-q8-etron": "car_images/AUDI/Audi Q6 e-tron.jpeg",
      "avinya-ev": "car_images/tata/tata_avinya_ev.jpeg",
      "be-07": "car_images/mahindra/mahindra_BE_07.jpeg",
      "be07": "car_images/mahindra/mahindra_BE_07.jpeg",
      "be6": "car_images/mahindra/mahindra-BE6.jpeg",
      "bmw-i4": "car_images/BMW/bmw_i4.jpeg",
      "bmw-i5": "car_images/BMW/BMW-I5.jpeg",
      "bmw-i7": "car_images/BMW/bmw_i7.jpeg",
      "bmw-ix": "car_images/BMW/BMW iX.jpeg",
      "bmw-ix1": "car_images/BMW/BMW iX1 LWB.jpeg",
      "bmw-ix1-lwb": "car_images/BMW/BMW iX1 LWB.jpeg",
      "byd-atto3": "car_images/BYD/BYD_atto.jpeg",
      "byd-emax-7": "car_images/BYD/BYD_eMAX_7.jpeg",
      "byd-emax7": "car_images/BYD/BYD_eMAX_7.jpeg",
      "byd-seal": "car_images/BYD/byd_seal.jpeg",
      "byd-sealion-6": "car_images/BYD/BYD-SEALION-6.jpeg",
      "byd-sealion-7": "car_images/BYD/BYD SEALION 7.jpeg",
      "byd-sealion7": "car_images/BYD/BYD SEALION 7.jpeg",
      "citroen-ec3": "car_images/CITROEN/Citroen_eC3.jpeg",
      "comet-ev": "car_images/MG/mg_comet_ev.webp",
      "creta-ev": "car_images/hyundai/Hyundai_Creta_Electric.jpeg",
      "curvv-ev": "car_images/tata/CURVE.jpeg",
      "cyberster": "car_images/MG/MG_Cyberster.jpeg",
      "d-max-ev": "car_images/ISUZU/D-MAX-EV.jpeg",
      "ec3": "car_images/CITROEN/Citroen_eC3.jpeg",
      "elevate-ev": "car_images/HONDA/honda_elevate_EV.jpeg",
      "etron-gt": "car_images/AUDI/audi_etron_gt.jpg",
      "ev6": "car_images/KIA/kia_ev6.jpeg",
      "ex90": "car_images/VOLVO/Volvo_EX90.jpeg",
      "fronx-ev": "car_images/maruti suzuki/fronx_ev.jpeg",
      "gv60": "car_images/GENESIS/GV60.jpeg",
      "harrier-ev": "car_images/tata/HARRIER.webp",
      "hyundai-creta-electric": "car_images/hyundai/Hyundai_Creta_Electric.jpeg",
      "ioniq-5": "car_images/hyundai/hyundai_ioniq5.jpeg",
      "ioniq-6": "car_images/hyundai/Hyundai_IONIQ6.jpeg",
      "jeep-avengers": "car_images/JEEP/Avengers.jpeg",
      "kia-carens-clavis-ev": "car_images/KIA/Kia Carens Clavis EV.WEBP",
      "kia-ev6": "car_images/KIA/kia_ev6.jpeg",
      "kia-ev9": "car_images/KIA/kia_ev9.jpeg",
      "lexus-es": "car_images/LEXUS/ES.jpeg",
      "lotus-eletre": "car_images/LOTUS/ELETRE.webp",
      "lotus-emeya": "car_images/LOTUS/EMEYA.jpeg",
      "luce": "car_images/ferrari/LUCE.jpeg",
      "m9-ev": "car_images/MG/MG_M9.jpeg",
      "macan-ev": "car_images/PORSCHE/porsche_maccan_EV.jpeg",
      "mahindra-thar-e": "car_images/mahindra/thar.e.jpeg",
      "mahindra-xev-7e": "car_images/mahindra/mahindra_XEV_9e.webp",
      "maruti-e-vitara": "car_images/maruti suzuki/maruti_evitara.jpeg",
      "maruti-jimny": "car_images/maruti suzuki/jimny.png",
      "mercedes-benz-amg-eqs": "car_images/MERCEDES_BENZ/AMG-EQS.jpeg",
      "mercedes-benz-c-class-ev": "car_images/MERCEDES_BENZ/C-CLASS.jpeg",
      "mercedes-benz-cla-ev": "car_images/MERCEDES_BENZ/Mercedes_Benz_CLA.jpeg",
      "mercedes-benz-eqs-maybach": "car_images/MERCEDES_BENZ/EQS=MAYBACH.webp",
      "mercedes-benz-eqs-suv": "car_images/MERCEDES_BENZ/Mercedes-Benz_EQS_SUV.jpeg",
      "mercedes-benz-eqs-suv-standard": "car_images/MERCEDES_BENZ/EQS_SUV.jpeg",
      "mercedes-benz-g-class-ev": "car_images/MERCEDES_BENZ/Mercedes-Benz_G-Class.jpeg",
      "mercedes-cla-electric": "car_images/MERCEDES_BENZ/Mercedes_Benz_CLA.jpeg",
      "mercedes-eqa": "car_images/MERCEDES_BENZ/C-CLASS.jpeg",
      "mercedes-eqe-suv": "car_images/MERCEDES_BENZ/EQS_SUV.jpeg",
      "mercedes-eqs": "car_images/MERCEDES_BENZ/Mercedes-Benz_EQS_SUV.jpeg",
      "mercedes-eqs-suv": "car_images/MERCEDES_BENZ/Mercedes-Benz_EQS_SUV.jpeg",
      "mercedes-g-class-electric": "car_images/MERCEDES_BENZ/Mercedes-Benz_G-Class.jpeg",
      "mg-cyberster": "car_images/MG/MG_Cyberster.jpeg",
      "mg-m9": "car_images/MG/MG_M9.jpeg",
      "mg-zs-ev": "car_images/MG/MG ZS EV.JPG",
      "mini-countryman-electric": "car_images/MINI /COUNTRYMAN-ELECTRIC.jpeg",
      "nexon-ev": "car_images/tata/NEXON.jpeg",
      "nissan-ariya": "car_images/NISSAN/Nissan_Ariya.jpeg",
      "nissan-leaf": "car_images/NISSAN/nissan_leaf.JPG",
      "pmv-eas-e": "car_images/PMV/EAS-E.jpeg",
      "porsche-cayenne-electric": "car_images/PORSCHE/PORSCHE_CAYENNE.jpeg",
      "porsche-cayenne-ev": "car_images/PORSCHE/PORSCHE_CAYENNE.jpeg",
      "porsche-macan-ev": "car_images/PORSCHE/porsche_maccan_EV.jpeg",
      "porsche-taycan": "car_images/PORSCHE/PORSCHE_TAYCAN.JPG",
      "pravaig-defy": "car_images/PRAVAIG/DEFY.jpeg",
      "punch-ev": "car_images/tata/PUNCH.jpeg",
      "renault-kwid-ev": "car_images/RENAULT/renault_kwid_ev.JPG",
      "rolls-royce-spectre": "car_images/ROLLS_ROYCE/Rolls-Royce Spectre.jpeg",
      "ryde": "car_images/BLINQ/RYDE.jpeg",
      "sierra-ev": "car_images/tata/SIERRA.jpeg",
      "skoda-elroq": "car_images/SKODA/Skoda_Elroq.jpeg",
      "skoda-enyaq": "car_images/SKODA/Skoda_Enyaq.JPG",
      "strom-r3": "car_images/STROM_MOTORS/R3.jpeg",
      "syros-ev": "car_images/KIA/Kia_syros_ev.jpeg",
      "tata-sierra-ev": "car_images/tata/SIERRA.jpeg",
      "tata-tigor-ev": "car_images/tata/TIAGO.jpeg",
      "tesla-model-y": "car_images/TESLA/MODEL-Y.jpeg",
      "thar-e": "car_images/mahindra/thar.e.jpeg",
      "tiago-ev": "car_images/tata/TIAGO.jpeg",
      "toyota-bz4x": "car_images/TOYOTA/Toyota_bZ4X.jpeg",
      "toyota-urban-cruiser-ev": "car_images/TOYOTA/Toyota_Urban_Cruiser.jpeg",
      "vayve-mobility-eva": "car_images/VAYVE_MOBILITY/eva.jpeg",
      "vinfast-vf-mpv7": "car_images/VINFAST/VinFast VF MPV7.JPG",
      "vinfast-vf3": "car_images/VINFAST/vin_fast_vf3.jpeg",
      "vinfast-vf6": "car_images/VINFAST/VinFast VF 6.jpeg",
      "vinfast-vf7": "car_images/VINFAST/vin_fast_vf7.jpeg",
      "volkswagen-id4": "car_images/VOLKSWAGAN/id_4.jpeg",
      "volvo-ec40": "car_images/VOLVO/volvo_EC40.WEBP",
      "volvo-ex30": "car_images/VOLVO/VOLVO_EX30.jpeg",
      "volvo-ex40": "car_images/VOLVO/VOLVO_EX40.JPG",
      "volvo-ex90": "car_images/VOLVO/Volvo_EX90.jpeg",
      "windsor-ev": "car_images/MG/MG_windsor_EV.jpeg",
      "xev-9e": "car_images/mahindra/mahindra_XEV_9e.webp",
      "xev-9s": "car_images/mahindra/Mahindra XEV 9s.png",
      "xpres-t-ev": "car_images/tata/EXPRESS-T.jpeg",
      "xuv-3xo-ev": "car_images/mahindra/3X0.jpeg",
      "xuv400": "car_images/mahindra/mahindra_XUV_400.jpg",
      "zero-alpha": "car_images/HONDA/ZERO_ALPHA.jpeg",
      "zs-ev": "car_images/MG/MG ZS EV.JPG",
};

module.exports = { S3_IMAGE_MAPPING };